apiVersion: v1
kind: Service
metadata:
  name: {{ include "monolith-chart.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}
