name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Decode and write GCP credentials
      run: echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 -d > ${{ github.workspace }}/gcp-key.json

    - name: ✅ Debug: Show decoded service account key
      run: cat ${{ github.workspace }}/gcp-key.json

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ github.workspace }}/gcp-key.json

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/monolith-app:$GITHUB_SHA .

    - name: Push Docker Image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/monolith-app:$GITHUB_SHA

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials monolith-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Helm Upgrade Monolith
      run: |
        helm upgrade --install monolith ./charts/monolith \
          --set image.repository=gcr.io/${{ secrets.GCP_PROJECT_ID }}/monolith-app \
          --set image.tag=$GITHUB_SHA
